import React from 'react';
import {createRoot} from 'react-dom/client';
import App from './App';
import './style.css';
import './jianwei-workspaces.css';
import './jianwei.css';
import './jianwei-motion.css';
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
import './jianwei-blueprint.css';
import './jianwei-polish.css';
import './jianwei-reference.css';
import './jianwei-typography.css';
